apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-cloudrun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-cloudrun
  template:
    metadata:
      labels:
        app: controller-cloudrun
    spec:
      containers:
      - name: controller
        image: controller:v1.0 # kpt-set: ${image-id}
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
        env:
        - name: PROJECT_ID
          value: project # kpt-set: ${project-id}
        - name: FIRESTORE_DATABASE
          value: "demo"
        - name: INSTANCE_COLLECTION
          value: "cr-instances"
        - name: LED_COLLECTION
          value: "cr"
        - name: GAMMA
          value: "20.0"
      serviceAccountName: sa # kpt-set: ${k-service-account}
