apiVersion: apps/v1
kind: Deployment
metadata:
  name: instance
spec:
  selector:
    matchLabels:
      app: instance
  template:
    metadata:
      labels:
        app: instance
    spec:
      containers:
      - name: instance
        image: instance:v1.0 # kpt-set: ${image-id}
        resources:
          limits:
            memory: "1Gi"
            cpu: "250m"
          requests:
            memory: "1Gi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 3
        env:
        - name: PROJECT_ID
          value: project # kpt-set: ${project-id}
        - name: FIRESTORE_DATABASE
          value: demo
        - name: INSTANCE_COLLECTION
          value: "gke-instances"
        - name: LED_COLLECTION
          value: "gke"
      serviceAccountName: sa # kpt-set: ${k-service-account}
